# Generated by Django 3.2.20 on 2023-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='../media/images/default_profile_o21i6o_h3tqjf', upload_to='images/'),
        ),
    ]
